/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedDividendsRouteImport } from './routes/_authenticated/dividends'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedRetirementRouteImport } from './routes/_authenticated/retirement'
import { Route as ApiPublicRefreshPricesRouteImport } from './routes/api/public/refresh-prices'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDividendsRoute = AuthenticatedDividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetirementRoute = AuthenticatedRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRefreshPricesRoute = ApiPublicRefreshPricesRouteImport.update({
  id: '/api/public/refresh-prices',
  path: '/api/public/refresh-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dividends': typeof AuthenticatedDividendsRoute
  '/import': typeof AuthenticatedImportRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dividends': typeof AuthenticatedDividendsRoute
  '/import': typeof AuthenticatedImportRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/retirement': typeof AuthenticatedRetirementRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dividends': typeof AuthenticatedDividendsRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/retirement': typeof AuthenticatedRetirementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/refresh-prices': typeof ApiPublicRefreshPricesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/dividends'
    | '/import'
    | '/invites'
    | '/ledger'
    | '/performance'
    | '/plan'
    | '/retirement'
    | '/api/public/refresh-prices'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/accounts'
    | '/dividends'
    | '/import'
    | '/invites'
    | '/ledger'
    | '/performance'
    | '/plan'
    | '/retirement'
    | '/'
    | '/api/public/refresh-prices'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/dividends'
    | '/_authenticated/import'
    | '/_authenticated/invites'
    | '/_authenticated/ledger'
    | '/_authenticated/performance'
    | '/_authenticated/plan'
    | '/_authenticated/retirement'
    | '/_authenticated/'
    | '/api/public/refresh-prices'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRefreshPricesRoute: typeof ApiPublicRefreshPricesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dividends': {
      id: '/_authenticated/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof AuthenticatedDividendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retirement': {
      id: '/_authenticated/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof AuthenticatedRetirementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/refresh-prices': {
      id: '/api/public/refresh-prices'
      path: '/api/public/refresh-prices'
      fullPath: '/api/public/refresh-prices'
      preLoaderRoute: typeof ApiPublicRefreshPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDividendsRoute: typeof AuthenticatedDividendsRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedRetirementRoute: typeof AuthenticatedRetirementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDividendsRoute: AuthenticatedDividendsRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedRetirementRoute: AuthenticatedRetirementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRefreshPricesRoute: ApiPublicRefreshPricesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
