// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getServerEnv(name: string): string | undefined {
  // `process` is not guaranteed to exist in a browser bundle. Keeping this
  // lookup guarded prevents auth initialization from throwing a ReferenceError.
  if (typeof process === "undefined") return undefined;
  return process.env[name];
}

// These are Supabase's public client values. They are intentionally safe to
// ship in the browser, unlike SUPABASE_SECRET_KEY or a service-role key.
const DEFAULT_SUPABASE_URL = "https://hksjusbiipwglybrudim.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  "sb_publishable_Q8eZUOZweZj3ztnNl3DpXw_-47Usv80";

function createSupabaseClient() {
  // Prefer deployment configuration, but keep a public fallback so a Vercel
  // deployment cannot take the entire login page down when VITE_* variables
  // were not added to the project environment.
  const SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"]?.trim() ||
    getServerEnv("SUPABASE_URL")?.trim() ||
    DEFAULT_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"]?.trim() ||
    getServerEnv("SUPABASE_PUBLISHABLE_KEY")?.trim() ||
    DEFAULT_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
